#!/usr/bin/python3
def rise_exception():
    raise typeError("this is a deliberate typeerror")
# uncomment the foolowing line if you want to test the function directly
#try:
# raise_exception()
# except TypeError as te:
#   print("Exception raised")   
